* class 1
* WFF = well formed formula, syntax and semantics
** if A and B are wff's and have the same truth table then A \equiv B
** if A \equiv T; then A is a tautology
   
* (P \land P \rightarrow Q) \rightarrow Q (if P and P implies Q then Q) 
** To show this:
*** Basic: write out truth table
*** Intermediate: solve equation to show (P \land P \rightarrow Q) \rightarrow Q \equiv T

* Atoms and Clauses 
** Atoms (A,B,\not A,\not B) 
** Clauses (A \lor B, A \land \not{}B, etc..)
** DNF(distrubated normal form) / Full DNF (look up the defn)

* Complete set of operators (can write every possible truth function)
** (e.g \lor and \not, or just nor/nand)


* Logic Systems
** Natural Deduction (Rules)
Not all rules are strictly necesary, but attempt to emulate how
actual deduction works
*** M.P: (Modus Ponens) P and P \rightarrow Q then Q
*** M.T: (Modus Tolens) P \rightarrow Q and \not Q then \not P
*** ADD:  A \rightarrow (A \lor B) , A \rightarrow (B \lor A)
*** CONJ: A, B \rightarrow A \land B
*** D.N: (double negation) \not\not{}A \rightarrow A, and reverse
*** CONT: A \land \not{}A \rightarrow F
*** SIMP: A \land B \rightarrow A, A \land B \rightarrow B
*** D.S: (Disjunctive Syllogism) (A \lor B) \land (\not A) \rightarrow B and reverse
*** C.P: (Conditional Proof) if we can derive B from A then we can say A \rightarrow B

*** H.S: (hypothitical syllogism) A\rightarrow{}B, B\rightarrow{}C, then A\rightarrow{}C
*** C.D: (constructive delema) A \lor B, A\rightarrow{}C, B\rightarrow{}D then C \lor D
*** Cases: A \lor B, A \rightarrow C, B \rightarrow C then C
** Incomplete logic system, has something that is a tautology which can't be proved 
** Inconsistant logic system, can prove something that isn't a tautology 

** (using C operators here)
prove (A | B) & !A & (B -> C) -> (B & C)
1. (A | B) & !A & (B -> C) P for C.P (premise for conditional proof)
2. A | B, 1 by SIMP
3. !A & B->C, 1 by SIMP
4. !A, 3 by SIMP
5. B->C, 1 by SIMP
6. B, 2,4 by D.S
7. C, 5,6 by M.P
8. B & C, 6,7 by CONJ
9 (A | B) & !A & (B->C) -> (B & C), 1,8 C.P
QED
** simplifications
A & B & C ... & N implies A, B, C, ... N
so still using above
1. A | B, P
2. !A, P
3. B->C, P
4. B, 1,2 D.S
5. C, 3,4, MP
6. B & C, 4,5 CONJ
QED, 1,2,3,6 CP

** (A | B -> C) & A  -> C
1. A|B->C, P
2. A, P
3. A|B, 2, ADD
4. C, 1,3 M.P
QED 1,2,3,4 M.P.
** Proof by Contradiction (I.P)
*** From \not A derive F
*** (A|B)&(B|C)&!C -> A
1. A|B, P
2. B->C, P
3. !C, P
4.     !A, P for I.P. //Start subproof
5.     B, 1,4 D.S
6.     C, 2,5 M.P
7.     F, 3,6 CONT
8. A, 4-7 I.P
QED 1,2,3,8 C.P.

*** (A|B -> C&D) -> (B->D)
1. A|B -> C&D, P for CP
2.           B, P for CP //subproof
3.           A|B, 1,2 by ADD
4.           C&D, by 1,3 MP
5.           D, 4 by SIMP
6. B->D, 2-5 CP
QED 1,6 C.P


# class 2

* class 2
NOTE: Not all in class examples copied.
* Subproofs
** when using proofs by contradiction or a cp proof within
another cp proof we use a subproof.
Subproofs basically exist within a nested lexical scope in the main proof
and `return` their last line.
ex. (A \lor B \rightarrow C \land D) \rightarrow (B \rightarrow D)
1. A \lor B \rightarrow C \land D, P
 subproof starts here
2.   B, P for CP
3.   A \lor B, 2 ADD
4.   C \land D, 1,3 MP
5.   D, 4 SIMP, Only this line is visable in the main proof
6. B \rightarrow D, 2-5 CP
QED 1,6 CP
* Introduce More Natural Deduction Rules 
(also added to Natural Deduction above)
** M.T (Modus Tolens): (P\not{}Q and \not{}Q then \not{}P)
** H.S (hypothitical syllogism) A\rightarrow{}B, B\rightarrow{}C, then A\rightarrow{}C
** C.D (constructive delema) A \lor B, A\rightarrow{}C, B\rightarrow{}D then C \lor D
** Cases: A \lor B, A \rightarrow C, B \rightarrow C then C

* defination of \equiv
** if A \equiv B then
A \rightarrow B and B \rightarrow A
thus if
A \rightarrow B and B \rightarrow A then A \equiv B

** show A \land A \equiv A
we don't have and identity, so this is weird
show A \land A \rightarrow A
1. A \land A, P for C.P
2. A,  SIMP
QED 1-2 CP
show A \rightarrow A \land A
1. A, P for CP
2. A \lor A, 1 add
3. A \land (A \lor A), 1,2 conj
4. A, 3 simp
5. A \land A, 1,4 add
QED 5, CP

* We lack predicates in Natural Deduction.
so for example,
All A can Q
B can't Q
B isn't A
can't be proven with our current logic
* for a predicate p(x) we can create propisitions in 3 ways
** plug in a value for x, i.e p(1);
** \forall{}x p(x), universal quantification
** \exists{}x p(x), existential quantification
** for this to make sense we need a Domain
i.e where do the values of x come from

* Predicates
** p(x) is a predicate
when x is filled in with a value it becomes a proposition
** Commonly used symbols
 x,y,z,... variables
 a,b,c,... constants
 p,q,<,>,... predicate names (p(),q() are propisitons, and are written p,q)
 f,g,max,min,+,-.. function names
 \exists, \forall Quantifiers
 punctuation (), ','
a term is a variable or constant or
a function applied to terms

atom is a predicate applied to terms

** predicate wffs
if W and V are wffs then:
 (W),\not{}W, W \land V, W \rightarrow V, etc... are wffs
 \exists{}xW, \forall{}xW are wffs
 predicates, functions, etc..
 combinations of the above

** precedence rules
1: \not \exists \forall
2: \land
3: \lor
4: \rightarrow
binary operators associate left to right
unary operators associate right to left
** Variable rules
the scope of the quantifer \exists{}x \forall{}x in \forall{}xP(x) is P(x)

the 'x' in \exists{}x is the variable the quantifier applies to,
we say that the x is bound to the quantifier. if a variable is not
bound it is free.

we can also bind variables by assigning them a constant value

if a wff has no free variables it is a proposition

in order for \exists{}x and \forall{}x to make sense we must have a 
domain of discourse(aka universe)

An interpretation of a wff consists of a domain D, together with the following:
assignment of symbols of the wff:
1. each predicate letter is assigned a predicate over D
2. each function lettel is assigned a function over D
3. each constant letter and each free variable is assigned a value in D

ex.
\forall{}x(p(a,x) \rightarrow \not{}q(f(x)))
1. D = N (natural numbers)
   a = 0
   p(z,w) = z < w
   q(w) = w<=2
   f(w) = w+1
\forall{}x(0 < x -> \not (x+1 <= 2))

if W is a wff and x is a free variable in W
(we normally write W(x)) and t is a term
then the wff that results from replacing x with t
is denoted W(x/t)

so the truth value of the wff \forall{}x(W(x)) with respect to the 
domain D is:
\forall{}xW(x) is true if W(x/d) is true for all d \epsilon D
ditto  for \exists

two wffs are equivlent if they are true with respect to every interpretation

since we can't actually test every interpretation we need to prove
that they are equivalent via Natural Deduction

\not (\forall{}xW) \equiv \exists{}x \not W
\not (\exists{}xW) \equiv \forall{}x \not W
\forall{}x\forall{}y W \equiv \forall{}y\forall{}x W
\exists{}x\exists{}y W \equiv \exists{}y\exists{}x W
\exists{}x (p(x) \rightarrow q(x)) \equiv \forall{}x p(x) \rightarrow \exists{}x q(x)

for Q in {\exists,\forall}
Qx(p(x) \lor q(x)) \equiv Qx p(x) \lor Qx q(x)
