;;need to make package for calculus and import it here
(load "calculus.lisp")
(defmacro array-len (y) '(array-total-size y))
(defun u-init (y) 
  (declare (type float y))
  (* -12 (expt (acos y) 2)))
(defun u-discrete (u h)
  (declare (type float-array u)
           (type float h))
  (let ((len (array-len u))
        (u-x (make-array len)))
    (dotimes (i len)
      (setf (svref u-x i) (+ (5pt-stencil i 3 u h)
                             (* (- 6) (aref u i) 
                                (5pt-stencil i 1 u h)))))
    (u-x)))
