/* This file is automatically generated, do not edit */
#ifndef __FDTD_CONSTS_H__
#define __FDTD_CONSTS_H__
static const double dx = 1.000000;
static const int num_writes = 5;
static const int threads = 3;
static const double mu = 0.0000012566370614;
static const double episilon = 0.0000000000088542;
static const double sigma = 10000000.000000;
static const int x_max = 20;static const int x_min = -20;
static const int y_max = 20;static const int y_min = -20;
static const int z_max = 20;static const int z_min = -20;
static const double dt = 0.001;
static const int grid_size = 64000;
static const double mu_dt = 0.0000012566370614;
#include <x86intrin.h>
#ifdef __AVX__
static const  __m256d mu_dt_simd = {0.000001,0.000001,0.000001,0.000001};
#endif
#endif