;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.2
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cl:defconstant _STDIO_H 1)

(cl:defconstant _FEATURES_H 1)

(cl:defconstant _DEFAULT_SOURCE 1)

(cl:defconstant _BSD_SOURCE 1)

(cl:defconstant _SVID_SOURCE 1)

(cl:defconstant __USE_POSIX_IMPLICITLY 1)

(cl:defconstant _POSIX_SOURCE 1)

(cl:defconstant _POSIX_C_SOURCE 200809L)

(cl:defconstant __USE_POSIX 1)

(cl:defconstant __USE_POSIX2 1)

(cl:defconstant __USE_POSIX199309 1)

(cl:defconstant __USE_POSIX199506 1)

(cl:defconstant __USE_XOPEN2K 1)

(cl:defconstant __USE_ISOC95 1)

(cl:defconstant __USE_ISOC99 1)

(cl:defconstant __USE_XOPEN2K8 1)

(cl:defconstant _ATFILE_SOURCE 1)

(cl:defconstant __USE_MISC 1)

(cl:defconstant __USE_BSD 1)

(cl:defconstant __USE_SVID 1)

(cl:defconstant __USE_ATFILE 1)

(cl:defconstant __USE_FORTIFY_LEVEL 0)

(cl:defconstant _STDC_PREDEF_H 1)

(cl:defconstant __STDC_IEC_559__ 1)

(cl:defconstant __STDC_IEC_559_COMPLEX__ 1)

(cl:defconstant __STDC_ISO_10646__ 201103L)

(cl:defconstant __STDC_NO_THREADS__ 1)

(cl:defconstant __GNU_LIBRARY__ 6)

(cl:defconstant __GLIBC__ 2)

(cl:defconstant __GLIBC_MINOR__ 19)

(cl:defconstant _SYS_CDEFS_H 1)

(cl:defconstant __WORDSIZE 32)

(cl:defconstant _BITS_TYPES_H 1)

(cl:defconstant _BITS_TYPESIZES_H 1)

(cl:defconstant __FD_SETSIZE 1024)

(cffi:defcstruct __fsid_t
	(__val :pointer))

(cl:defconstant __FILE_defined 1)

(cl:defconstant ____FILE_defined 1)

(cl:defconstant _G_config_h 1)

(cl:defconstant ____mbstate_t_defined 1)

(cffi:defcstruct __mbstate_t
	(__count :int)
	(__value :pointer))

(cffi:defcunion __mbstate_t___value
	(__wch :unsigned-int)
	(__wchb :pointer))

(cffi:defcstruct _G_fpos_t
	(__pos :long)
	(__state __mbstate_t))

(cffi:defcstruct _G_fpos64_t
	(__pos :long-long)
	(__state __mbstate_t))

(cl:defconstant _G_HAVE_MMAP 1)

(cl:defconstant _G_HAVE_MREMAP 1)

(cl:defconstant _G_IO_IO_FILE_VERSION #x20001)

(cl:defconstant _G_BUFSIZ 8192)

(cl:defconstant _IO_BUFSIZ 8192)

(cl:defconstant _IO_UNIFIED_JUMPTABLES 1)

(cl:defconstant EOF -1)

(cl:defconstant _IOS_INPUT 1)

(cl:defconstant _IOS_OUTPUT 2)

(cl:defconstant _IOS_ATEND 4)

(cl:defconstant _IOS_APPEND 8)

(cl:defconstant _IOS_TRUNC 16)

(cl:defconstant _IOS_NOCREATE 32)

(cl:defconstant _IOS_NOREPLACE 64)

(cl:defconstant _IOS_BIN 128)

(cl:defconstant _IO_MAGIC #xFBAD0000)

(cl:defconstant _OLD_STDIO_MAGIC #xFABC0000)

(cl:defconstant _IO_MAGIC_MASK #xFFFF0000)

(cl:defconstant _IO_USER_BUF 1)

(cl:defconstant _IO_UNBUFFERED 2)

(cl:defconstant _IO_NO_READS 4)

(cl:defconstant _IO_NO_WRITES 8)

(cl:defconstant _IO_EOF_SEEN #x10)

(cl:defconstant _IO_ERR_SEEN #x20)

(cl:defconstant _IO_DELETE_DONT_CLOSE #x40)

(cl:defconstant _IO_LINKED #x80)

(cl:defconstant _IO_IN_BACKUP #x100)

(cl:defconstant _IO_LINE_BUF #x200)

(cl:defconstant _IO_TIED_PUT_GET #x400)

(cl:defconstant _IO_CURRENTLY_PUTTING #x800)

(cl:defconstant _IO_IS_APPENDING #x1000)

(cl:defconstant _IO_IS_FILEBUF #x2000)

(cl:defconstant _IO_BAD_SEEN #x4000)

(cl:defconstant _IO_USER_LOCK #x8000)

(cl:defconstant _IO_FLAGS2_MMAP 1)

(cl:defconstant _IO_FLAGS2_NOTCANCEL 2)

(cl:defconstant _IO_FLAGS2_USER_WBUF 8)

(cl:defconstant _IO_SKIPWS #o1)

(cl:defconstant _IO_LEFT #o2)

(cl:defconstant _IO_RIGHT #o4)

(cl:defconstant _IO_INTERNAL #o10)

(cl:defconstant _IO_DEC #o20)

(cl:defconstant _IO_OCT #o40)

(cl:defconstant _IO_HEX #o100)

(cl:defconstant _IO_SHOWBASE #o200)

(cl:defconstant _IO_SHOWPOINT #o400)

(cl:defconstant _IO_UPPERCASE #o1000)

(cl:defconstant _IO_SHOWPOS #o2000)

(cl:defconstant _IO_SCIENTIFIC #o4000)

(cl:defconstant _IO_FIXED #o10000)

(cl:defconstant _IO_UNITBUF #o20000)

(cl:defconstant _IO_STDIO #o40000)

(cl:defconstant _IO_DONT_CLOSE #o100000)

(cl:defconstant _IO_BOOLALPHA #o200000)

(cffi:defcstruct _IO_marker
	(_next :pointer)
	(_sbuf :pointer)
	(_pos :int))

(cffi:defcenum __codecvt_result
	:__codecvt_ok
	:__codecvt_partial
	:__codecvt_error
	:__codecvt_noconv)

(cffi:defcstruct _IO_FILE
	(_flags :int)
	(_IO_read_ptr :string)
	(_IO_read_end :string)
	(_IO_read_base :string)
	(_IO_write_base :string)
	(_IO_write_ptr :string)
	(_IO_write_end :string)
	(_IO_buf_base :string)
	(_IO_buf_end :string)
	(_IO_save_base :string)
	(_IO_backup_base :string)
	(_IO_save_end :string)
	(_markers :pointer)
	(_chain :pointer)
	(_fileno :int)
	(_flags2 :int)
	(_old_offset :long)
	(_cur_column :unsigned-short)
	(_vtable_offset :char)
	(_shortbuf :pointer)
	(_lock :pointer)
	(_offset :long-long)
	(__pad1 :pointer)
	(__pad2 :pointer)
	(__pad3 :pointer)
	(__pad4 :pointer)
	(__pad5 :unsigned-long)
	(_mode :int)
	(_unused2 :pointer))

(cffi:defcvar ("_IO_2_1_stdin_" _IO_2_1_stdin_)
 :pointer)

(cffi:defcvar ("_IO_2_1_stdout_" _IO_2_1_stdout_)
 :pointer)

(cffi:defcvar ("_IO_2_1_stderr_" _IO_2_1_stderr_)
 :pointer)

(cffi:defcfun ("__underflow" __underflow) :int
  (arg0 :pointer))

(cffi:defcfun ("__uflow" __uflow) :int
  (arg0 :pointer))

(cffi:defcfun ("__overflow" __overflow) :int
  (arg0 :pointer)
  (arg1 :int))

(cffi:defcfun ("_IO_getc" _IO_getc) :int
  (__fp :pointer))

(cffi:defcfun ("_IO_putc" _IO_putc) :int
  (__c :int)
  (__fp :pointer))

(cffi:defcfun ("_IO_feof" _IO_feof) :int
  (__fp :pointer))

(cffi:defcfun ("_IO_ferror" _IO_ferror) :int
  (__fp :pointer))

(cffi:defcfun ("_IO_peekc_locked" _IO_peekc_locked) :int
  (__fp :pointer))

(cffi:defcfun ("_IO_flockfile" _IO_flockfile) :void
  (arg0 :pointer))

(cffi:defcfun ("_IO_funlockfile" _IO_funlockfile) :void
  (arg0 :pointer))

(cffi:defcfun ("_IO_ftrylockfile" _IO_ftrylockfile) :int
  (arg0 :pointer))

(cffi:defcfun ("_IO_vfscanf" _IO_vfscanf) :int
  (arg0 :pointer)
  (arg1 :string)
  (arg2 :pointer)
  (arg3 :pointer))

(cffi:defcfun ("_IO_vfprintf" _IO_vfprintf) :int
  (arg0 :pointer)
  (arg1 :string)
  (arg2 :pointer))

(cffi:defcfun ("_IO_padn" _IO_padn) :int
  (arg0 :pointer)
  (arg1 :int)
  (arg2 :int))

(cffi:defcfun ("_IO_sgetn" _IO_sgetn) :unsigned-long
  (arg0 :pointer)
  (arg1 :pointer)
  (arg2 :unsigned-long))

(cffi:defcfun ("_IO_seekoff" _IO_seekoff) :long-long
  (arg0 :pointer)
  (arg1 :long-long)
  (arg2 :int)
  (arg3 :int))

(cffi:defcfun ("_IO_seekpos" _IO_seekpos) :long-long
  (arg0 :pointer)
  (arg1 :long-long)
  (arg2 :int))

(cffi:defcfun ("_IO_free_backup_area" _IO_free_backup_area) :void
  (arg0 :pointer))

(cl:defconstant _IOFBF 0)

(cl:defconstant _IOLBF 1)

(cl:defconstant _IONBF 2)

(cl:defconstant BUFSIZ 8192)

(cl:defconstant SEEK_SET 0)

(cl:defconstant SEEK_CUR 1)

(cl:defconstant SEEK_END 2)

(cl:defconstant P_tmpdir "/tmp")

(cl:defconstant L_tmpnam 20)

(cl:defconstant TMP_MAX 238328)

(cl:defconstant FILENAME_MAX 4096)

(cl:defconstant L_ctermid 9)

(cl:defconstant FOPEN_MAX 16)

(cffi:defcvar ("stdin" stdin)
 :pointer)

(cffi:defcvar ("stdout" stdout)
 :pointer)

(cffi:defcvar ("stderr" stderr)
 :pointer)

(cffi:defcfun ("remove" remove) :int
  (__filename :string))

(cffi:defcfun ("rename" rename) :int
  (__old :string)
  (__new :string))

(cffi:defcfun ("renameat" renameat) :int
  (__oldfd :int)
  (__old :string)
  (__newfd :int)
  (__new :string))

(cffi:defcfun ("tmpfile" tmpfile) :pointer)

(cffi:defcfun ("tmpnam" tmpnam) :string
  (__s :string))

(cffi:defcfun ("tmpnam_r" tmpnam_r) :string
  (__s :string))

(cffi:defcfun ("tempnam" tempnam) :string
  (__dir :string)
  (__pfx :string))

(cffi:defcfun ("fclose" fclose) :int
  (__stream :pointer))

(cffi:defcfun ("fflush" fflush) :int
  (__stream :pointer))

(cffi:defcfun ("fflush_unlocked" fflush_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("fopen" fopen) :pointer
  (__filename :string)
  (__modes :string))

(cffi:defcfun ("freopen" freopen) :pointer
  (__filename :string)
  (__modes :string)
  (__stream :pointer))

(cffi:defcfun ("fdopen" fdopen) :pointer
  (__fd :int)
  (__modes :string))

(cffi:defcfun ("fmemopen" fmemopen) :pointer
  (__s :pointer)
  (__len :unsigned-long)
  (__modes :string))

(cffi:defcfun ("open_memstream" open_memstream) :pointer
  (__bufloc :pointer)
  (__sizeloc :pointer))

(cffi:defcfun ("setbuf" setbuf) :void
  (__stream :pointer)
  (__buf :string))

(cffi:defcfun ("setvbuf" setvbuf) :int
  (__stream :pointer)
  (__buf :string)
  (__modes :int)
  (__n :unsigned-long))

(cffi:defcfun ("setbuffer" setbuffer) :void
  (__stream :pointer)
  (__buf :string)
  (__size :unsigned-long))

(cffi:defcfun ("setlinebuf" setlinebuf) :void
  (__stream :pointer))

(cffi:defcfun ("fprintf" fprintf) :int
  (__stream :pointer)
  (__format :string)
  &rest)

(cffi:defcfun ("printf" printf) :int
  (__format :string)
  &rest)

(cffi:defcfun ("sprintf" sprintf) :int
  (__s :string)
  (__format :string)
  &rest)

(cffi:defcfun ("vfprintf" vfprintf) :int
  (__s :pointer)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("vprintf" vprintf) :int
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("vsprintf" vsprintf) :int
  (__s :string)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("snprintf" snprintf) :int
  (__s :string)
  (__maxlen :unsigned-long)
  (__format :string)
  &rest)

(cffi:defcfun ("vsnprintf" vsnprintf) :int
  (__s :string)
  (__maxlen :unsigned-long)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("vdprintf" vdprintf) :int
  (__fd :int)
  (__fmt :string)
  (__arg :pointer))

(cffi:defcfun ("dprintf" dprintf) :int
  (__fd :int)
  (__fmt :string)
  &rest)

(cffi:defcfun ("fscanf" fscanf) :int
  (__stream :pointer)
  (__format :string)
  &rest)

(cffi:defcfun ("scanf" scanf) :int
  (__format :string)
  &rest)

(cffi:defcfun ("sscanf" sscanf) :int
  (__s :string)
  (__format :string)
  &rest)

(cffi:defcfun ("__isoc99_fscanf" __isoc99_fscanf) :int
  (__stream :pointer)
  (__format :string)
  &rest)

(cffi:defcfun ("__isoc99_scanf" __isoc99_scanf) :int
  (__format :string)
  &rest)

(cffi:defcfun ("__isoc99_sscanf" __isoc99_sscanf) :int
  (__s :string)
  (__format :string)
  &rest)

(cffi:defcfun ("vfscanf" vfscanf) :int
  (__s :pointer)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("vscanf" vscanf) :int
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("vsscanf" vsscanf) :int
  (__s :string)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("__isoc99_vfscanf" __isoc99_vfscanf) :int
  (__s :pointer)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("__isoc99_vscanf" __isoc99_vscanf) :int
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("__isoc99_vsscanf" __isoc99_vsscanf) :int
  (__s :string)
  (__format :string)
  (__arg :pointer))

(cffi:defcfun ("fgetc" fgetc) :int
  (__stream :pointer))

(cffi:defcfun ("getc" getc) :int
  (__stream :pointer))

(cffi:defcfun ("getchar" getchar) :int)

(cffi:defcfun ("getc_unlocked" getc_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("getchar_unlocked" getchar_unlocked) :int)

(cffi:defcfun ("fgetc_unlocked" fgetc_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("fputc" fputc) :int
  (__c :int)
  (__stream :pointer))

(cffi:defcfun ("putc" putc) :int
  (__c :int)
  (__stream :pointer))

(cffi:defcfun ("putchar" putchar) :int
  (__c :int))

(cffi:defcfun ("fputc_unlocked" fputc_unlocked) :int
  (__c :int)
  (__stream :pointer))

(cffi:defcfun ("putc_unlocked" putc_unlocked) :int
  (__c :int)
  (__stream :pointer))

(cffi:defcfun ("putchar_unlocked" putchar_unlocked) :int
  (__c :int))

(cffi:defcfun ("getw" getw) :int
  (__stream :pointer))

(cffi:defcfun ("putw" putw) :int
  (__w :int)
  (__stream :pointer))

(cffi:defcfun ("fgets" fgets) :string
  (__s :string)
  (__n :int)
  (__stream :pointer))

(cffi:defcfun ("gets" gets) :string
  (__s :string))

(cffi:defcfun ("__getdelim" __getdelim) :int
  (__lineptr :pointer)
  (__n :pointer)
  (__delimiter :int)
  (__stream :pointer))

(cffi:defcfun ("getdelim" getdelim) :int
  (__lineptr :pointer)
  (__n :pointer)
  (__delimiter :int)
  (__stream :pointer))

(cffi:defcfun ("getline" getline) :int
  (__lineptr :pointer)
  (__n :pointer)
  (__stream :pointer))

(cffi:defcfun ("fputs" fputs) :int
  (__s :string)
  (__stream :pointer))

(cffi:defcfun ("puts" puts) :int
  (__s :string))

(cffi:defcfun ("ungetc" ungetc) :int
  (__c :int)
  (__stream :pointer))

(cffi:defcfun ("fread" fread) :unsigned-long
  (__ptr :pointer)
  (__size :unsigned-long)
  (__n :unsigned-long)
  (__stream :pointer))

(cffi:defcfun ("fwrite" fwrite) :unsigned-long
  (__ptr :pointer)
  (__size :unsigned-long)
  (__n :unsigned-long)
  (__s :pointer))

(cffi:defcfun ("fread_unlocked" fread_unlocked) :unsigned-long
  (__ptr :pointer)
  (__size :unsigned-long)
  (__n :unsigned-long)
  (__stream :pointer))

(cffi:defcfun ("fwrite_unlocked" fwrite_unlocked) :unsigned-long
  (__ptr :pointer)
  (__size :unsigned-long)
  (__n :unsigned-long)
  (__stream :pointer))

(cffi:defcfun ("fseek" fseek) :int
  (__stream :pointer)
  (__off :long)
  (__whence :int))

(cffi:defcfun ("ftell" ftell) :long
  (__stream :pointer))

(cffi:defcfun ("rewind" rewind) :void
  (__stream :pointer))

(cffi:defcfun ("fseeko" fseeko) :int
  (__stream :pointer)
  (__off :long)
  (__whence :int))

(cffi:defcfun ("ftello" ftello) :long
  (__stream :pointer))

(cffi:defcfun ("fgetpos" fgetpos) :int
  (__stream :pointer)
  (__pos :pointer))

(cffi:defcfun ("fsetpos" fsetpos) :int
  (__stream :pointer)
  (__pos :pointer))

(cffi:defcfun ("clearerr" clearerr) :void
  (__stream :pointer))

(cffi:defcfun ("feof" feof) :int
  (__stream :pointer))

(cffi:defcfun ("ferror" ferror) :int
  (__stream :pointer))

(cffi:defcfun ("clearerr_unlocked" clearerr_unlocked) :void
  (__stream :pointer))

(cffi:defcfun ("feof_unlocked" feof_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("ferror_unlocked" ferror_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("perror" perror) :void
  (__s :string))

(cffi:defcvar ("sys_nerr" sys_nerr)
 :int)

(cffi:defcvar ("sys_errlist" sys_errlist)
 :pointer)

(cffi:defcfun ("fileno" fileno) :int
  (__stream :pointer))

(cffi:defcfun ("fileno_unlocked" fileno_unlocked) :int
  (__stream :pointer))

(cffi:defcfun ("popen" popen) :pointer
  (__command :string)
  (__modes :string))

(cffi:defcfun ("pclose" pclose) :int
  (__stream :pointer))

(cffi:defcfun ("ctermid" ctermid) :string
  (__s :string))

(cffi:defcfun ("flockfile" flockfile) :void
  (__stream :pointer))

(cffi:defcfun ("ftrylockfile" ftrylockfile) :int
  (__stream :pointer))

(cffi:defcfun ("funlockfile" funlockfile) :void
  (__stream :pointer))

(cl:defconstant _UNISTD_H 1)

(cl:defconstant _POSIX_VERSION 200809L)

(cl:defconstant __POSIX2_THIS_VERSION 200809L)

(cl:defconstant _POSIX2_VERSION 200809L)

(cl:defconstant _POSIX2_C_BIND 200809L)

(cl:defconstant _POSIX2_C_DEV 200809L)

(cl:defconstant _POSIX2_SW_DEV 200809L)

(cl:defconstant _POSIX2_LOCALEDEF 200809L)

(cl:defconstant _XOPEN_VERSION 700)

(cl:defconstant _XOPEN_XCU_VERSION 4)

(cl:defconstant _XOPEN_XPG2 1)

(cl:defconstant _XOPEN_XPG3 1)

(cl:defconstant _XOPEN_XPG4 1)

(cl:defconstant _XOPEN_UNIX 1)

(cl:defconstant _XOPEN_CRYPT 1)

(cl:defconstant _XOPEN_ENH_I18N 1)

(cl:defconstant _XOPEN_LEGACY 1)

(cl:defconstant _BITS_POSIX_OPT_H 1)

(cl:defconstant _POSIX_JOB_CONTROL 1)

(cl:defconstant _POSIX_SAVED_IDS 1)

(cl:defconstant _POSIX_PRIORITY_SCHEDULING 200809L)

(cl:defconstant _POSIX_SYNCHRONIZED_IO 200809L)

(cl:defconstant _POSIX_FSYNC 200809L)

(cl:defconstant _POSIX_MAPPED_FILES 200809L)

(cl:defconstant _POSIX_MEMLOCK 200809L)

(cl:defconstant _POSIX_MEMLOCK_RANGE 200809L)

(cl:defconstant _POSIX_MEMORY_PROTECTION 200809L)

(cl:defconstant _POSIX_CHOWN_RESTRICTED 0)

(cl:defconstant _POSIX_VDISABLE #\\)

(cl:defconstant _POSIX_NO_TRUNC 1)

(cl:defconstant _XOPEN_REALTIME 1)

(cl:defconstant _XOPEN_REALTIME_THREADS 1)

(cl:defconstant _XOPEN_SHM 1)

(cl:defconstant _POSIX_THREADS 200809L)

(cl:defconstant _POSIX_REENTRANT_FUNCTIONS 1)

(cl:defconstant _POSIX_THREAD_SAFE_FUNCTIONS 200809L)

(cl:defconstant _POSIX_THREAD_PRIORITY_SCHEDULING 200809L)

(cl:defconstant _POSIX_THREAD_ATTR_STACKSIZE 200809L)

(cl:defconstant _POSIX_THREAD_ATTR_STACKADDR 200809L)

(cl:defconstant _POSIX_THREAD_PRIO_INHERIT 200809L)

(cl:defconstant _POSIX_THREAD_PRIO_PROTECT 200809L)

(cl:defconstant _POSIX_THREAD_ROBUST_PRIO_INHERIT 200809L)

(cl:defconstant _POSIX_THREAD_ROBUST_PRIO_PROTECT -1)

(cl:defconstant _POSIX_SEMAPHORES 200809L)

(cl:defconstant _POSIX_REALTIME_SIGNALS 200809L)

(cl:defconstant _POSIX_ASYNCHRONOUS_IO 200809L)

(cl:defconstant _POSIX_ASYNC_IO 1)

(cl:defconstant _LFS_ASYNCHRONOUS_IO 1)

(cl:defconstant _POSIX_PRIORITIZED_IO 200809L)

(cl:defconstant _LFS64_ASYNCHRONOUS_IO 1)

(cl:defconstant _LFS_LARGEFILE 1)

(cl:defconstant _LFS64_LARGEFILE 1)

(cl:defconstant _LFS64_STDIO 1)

(cl:defconstant _POSIX_SHARED_MEMORY_OBJECTS 200809L)

(cl:defconstant _POSIX_CPUTIME 0)

(cl:defconstant _POSIX_THREAD_CPUTIME 0)

(cl:defconstant _POSIX_REGEXP 1)

(cl:defconstant _POSIX_READER_WRITER_LOCKS 200809L)

(cl:defconstant _POSIX_SHELL 1)

(cl:defconstant _POSIX_TIMEOUTS 200809L)

(cl:defconstant _POSIX_SPIN_LOCKS 200809L)

(cl:defconstant _POSIX_SPAWN 200809L)

(cl:defconstant _POSIX_TIMERS 200809L)

(cl:defconstant _POSIX_BARRIERS 200809L)

(cl:defconstant _POSIX_MESSAGE_PASSING 200809L)

(cl:defconstant _POSIX_THREAD_PROCESS_SHARED 200809L)

(cl:defconstant _POSIX_MONOTONIC_CLOCK 0)

(cl:defconstant _POSIX_CLOCK_SELECTION 200809L)

(cl:defconstant _POSIX_ADVISORY_INFO 200809L)

(cl:defconstant _POSIX_IPV6 200809L)

(cl:defconstant _POSIX_RAW_SOCKETS 200809L)

(cl:defconstant _POSIX2_CHAR_TERM 200809L)

(cl:defconstant _POSIX_SPORADIC_SERVER -1)

(cl:defconstant _POSIX_THREAD_SPORADIC_SERVER -1)

(cl:defconstant _POSIX_TRACE -1)

(cl:defconstant _POSIX_TRACE_EVENT_FILTER -1)

(cl:defconstant _POSIX_TRACE_INHERIT -1)

(cl:defconstant _POSIX_TRACE_LOG -1)

(cl:defconstant _POSIX_TYPED_MEMORY_OBJECTS -1)

(cl:defconstant _POSIX_V7_ILP32_OFFBIG 1)

(cl:defconstant _POSIX_V6_ILP32_OFFBIG 1)

(cl:defconstant _XBS5_ILP32_OFFBIG 1)

(cl:defconstant _POSIX_V7_ILP32_OFF32 1)

(cl:defconstant _POSIX_V6_ILP32_OFF32 1)

(cl:defconstant _XBS5_ILP32_OFF32 1)

(cl:defconstant __ILP32_OFF32_CFLAGS "-m32")

(cl:defconstant __ILP32_OFF32_LDFLAGS "-m32")

(cl:defconstant __ILP32_OFFBIG_CFLAGS "-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64")

(cl:defconstant __ILP32_OFFBIG_LDFLAGS "-m32")

(cl:defconstant __LP64_OFF64_CFLAGS "-m64")

(cl:defconstant __LP64_OFF64_LDFLAGS "-m64")

(cl:defconstant STDIN_FILENO 0)

(cl:defconstant STDOUT_FILENO 1)

(cl:defconstant STDERR_FILENO 2)

(cl:defconstant R_OK 4)

(cl:defconstant W_OK 2)

(cl:defconstant X_OK 1)

(cl:defconstant F_OK 0)

(cffi:defcfun ("access" access) :int
  (__name :string)
  (__type :int))

(cffi:defcfun ("faccessat" faccessat) :int
  (__fd :int)
  (__file :string)
  (__type :int)
  (__flag :int))

(cl:defconstant L_SET 0)

(cl:defconstant L_INCR 1)

(cl:defconstant L_XTND 2)

(cffi:defcfun ("lseek" lseek) :long
  (__fd :int)
  (__offset :long)
  (__whence :int))

(cffi:defcfun ("close" close) :int
  (__fd :int))

(cffi:defcfun ("read" read) :int
  (__fd :int)
  (__buf :pointer)
  (__nbytes :unsigned-long))

(cffi:defcfun ("write" write) :int
  (__fd :int)
  (__buf :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("pread" pread) :int
  (__fd :int)
  (__buf :pointer)
  (__nbytes :unsigned-long)
  (__offset :long))

(cffi:defcfun ("pwrite" pwrite) :int
  (__fd :int)
  (__buf :pointer)
  (__n :unsigned-long)
  (__offset :long))

(cffi:defcfun ("pipe" pipe) :int
  (__pipedes :pointer))

(cffi:defcfun ("alarm" alarm) :unsigned-int
  (__seconds :unsigned-int))

(cffi:defcfun ("sleep" sleep) :unsigned-int
  (__seconds :unsigned-int))

(cffi:defcfun ("ualarm" ualarm) :unsigned-int
  (__value :unsigned-int)
  (__interval :unsigned-int))

(cffi:defcfun ("usleep" usleep) :int
  (__useconds :unsigned-int))

(cffi:defcfun ("pause" pause) :int)

(cffi:defcfun ("chown" chown) :int
  (__file :string)
  (__owner :unsigned-int)
  (__group :unsigned-int))

(cffi:defcfun ("fchown" fchown) :int
  (__fd :int)
  (__owner :unsigned-int)
  (__group :unsigned-int))

(cffi:defcfun ("lchown" lchown) :int
  (__file :string)
  (__owner :unsigned-int)
  (__group :unsigned-int))

(cffi:defcfun ("fchownat" fchownat) :int
  (__fd :int)
  (__file :string)
  (__owner :unsigned-int)
  (__group :unsigned-int)
  (__flag :int))

(cffi:defcfun ("chdir" chdir) :int
  (__path :string))

(cffi:defcfun ("fchdir" fchdir) :int
  (__fd :int))

(cffi:defcfun ("getcwd" getcwd) :string
  (__buf :string)
  (__size :unsigned-long))

(cffi:defcfun ("getwd" getwd) :string
  (__buf :string))

(cffi:defcfun ("dup" dup) :int
  (__fd :int))

(cffi:defcfun ("dup2" dup2) :int
  (__fd :int)
  (__fd2 :int))

(cffi:defcvar ("__environ" __environ)
 :pointer)

(cffi:defcfun ("execve" execve) :int
  (__path :string)
  (__argv :pointer)
  (__envp :pointer))

(cffi:defcfun ("fexecve" fexecve) :int
  (__fd :int)
  (__argv :pointer)
  (__envp :pointer))

(cffi:defcfun ("execv" execv) :int
  (__path :string)
  (__argv :pointer))

(cffi:defcfun ("execle" execle) :int
  (__path :string)
  (__arg :string)
  &rest)

(cffi:defcfun ("execl" execl) :int
  (__path :string)
  (__arg :string)
  &rest)

(cffi:defcfun ("execvp" execvp) :int
  (__file :string)
  (__argv :pointer))

(cffi:defcfun ("execlp" execlp) :int
  (__file :string)
  (__arg :string)
  &rest)

(cffi:defcfun ("nice" nice) :int
  (__inc :int))

(cffi:defcfun ("_exit" _exit) :void
  (__status :int))

(defanonenum 
	_PC_LINK_MAX
	_PC_MAX_CANON
	_PC_MAX_INPUT
	_PC_NAME_MAX
	_PC_PATH_MAX
	_PC_PIPE_BUF
	_PC_CHOWN_RESTRICTED
	_PC_NO_TRUNC
	_PC_VDISABLE
	_PC_SYNC_IO
	_PC_ASYNC_IO
	_PC_PRIO_IO
	_PC_SOCK_MAXBUF
	_PC_FILESIZEBITS
	_PC_REC_INCR_XFER_SIZE
	_PC_REC_MAX_XFER_SIZE
	_PC_REC_MIN_XFER_SIZE
	_PC_REC_XFER_ALIGN
	_PC_ALLOC_SIZE_MIN
	_PC_SYMLINK_MAX
	_PC_2_SYMLINKS)

(defanonenum 
	_SC_ARG_MAX
	_SC_CHILD_MAX
	_SC_CLK_TCK
	_SC_NGROUPS_MAX
	_SC_OPEN_MAX
	_SC_STREAM_MAX
	_SC_TZNAME_MAX
	_SC_JOB_CONTROL
	_SC_SAVED_IDS
	_SC_REALTIME_SIGNALS
	_SC_PRIORITY_SCHEDULING
	_SC_TIMERS
	_SC_ASYNCHRONOUS_IO
	_SC_PRIORITIZED_IO
	_SC_SYNCHRONIZED_IO
	_SC_FSYNC
	_SC_MAPPED_FILES
	_SC_MEMLOCK
	_SC_MEMLOCK_RANGE
	_SC_MEMORY_PROTECTION
	_SC_MESSAGE_PASSING
	_SC_SEMAPHORES
	_SC_SHARED_MEMORY_OBJECTS
	_SC_AIO_LISTIO_MAX
	_SC_AIO_MAX
	_SC_AIO_PRIO_DELTA_MAX
	_SC_DELAYTIMER_MAX
	_SC_MQ_OPEN_MAX
	_SC_MQ_PRIO_MAX
	_SC_VERSION
	_SC_PAGESIZE
	_SC_RTSIG_MAX
	_SC_SEM_NSEMS_MAX
	_SC_SEM_VALUE_MAX
	_SC_SIGQUEUE_MAX
	_SC_TIMER_MAX
	_SC_BC_BASE_MAX
	_SC_BC_DIM_MAX
	_SC_BC_SCALE_MAX
	_SC_BC_STRING_MAX
	_SC_COLL_WEIGHTS_MAX
	_SC_EQUIV_CLASS_MAX
	_SC_EXPR_NEST_MAX
	_SC_LINE_MAX
	_SC_RE_DUP_MAX
	_SC_CHARCLASS_NAME_MAX
	_SC_2_VERSION
	_SC_2_C_BIND
	_SC_2_C_DEV
	_SC_2_FORT_DEV
	_SC_2_FORT_RUN
	_SC_2_SW_DEV
	_SC_2_LOCALEDEF
	_SC_PII
	_SC_PII_XTI
	_SC_PII_SOCKET
	_SC_PII_INTERNET
	_SC_PII_OSI
	_SC_POLL
	_SC_SELECT
	_SC_UIO_MAXIOV
	(_SC_IOV_MAX #._SC_UIO_MAXIOV)
	_SC_PII_INTERNET_STREAM
	_SC_PII_INTERNET_DGRAM
	_SC_PII_OSI_COTS
	_SC_PII_OSI_CLTS
	_SC_PII_OSI_M
	_SC_T_IOV_MAX
	_SC_THREADS
	_SC_THREAD_SAFE_FUNCTIONS
	_SC_GETGR_R_SIZE_MAX
	_SC_GETPW_R_SIZE_MAX
	_SC_LOGIN_NAME_MAX
	_SC_TTY_NAME_MAX
	_SC_THREAD_DESTRUCTOR_ITERATIONS
	_SC_THREAD_KEYS_MAX
	_SC_THREAD_STACK_MIN
	_SC_THREAD_THREADS_MAX
	_SC_THREAD_ATTR_STACKADDR
	_SC_THREAD_ATTR_STACKSIZE
	_SC_THREAD_PRIORITY_SCHEDULING
	_SC_THREAD_PRIO_INHERIT
	_SC_THREAD_PRIO_PROTECT
	_SC_THREAD_PROCESS_SHARED
	_SC_NPROCESSORS_CONF
	_SC_NPROCESSORS_ONLN
	_SC_PHYS_PAGES
	_SC_AVPHYS_PAGES
	_SC_ATEXIT_MAX
	_SC_PASS_MAX
	_SC_XOPEN_VERSION
	_SC_XOPEN_XCU_VERSION
	_SC_XOPEN_UNIX
	_SC_XOPEN_CRYPT
	_SC_XOPEN_ENH_I18N
	_SC_XOPEN_SHM
	_SC_2_CHAR_TERM
	_SC_2_C_VERSION
	_SC_2_UPE
	_SC_XOPEN_XPG2
	_SC_XOPEN_XPG3
	_SC_XOPEN_XPG4
	_SC_CHAR_BIT
	_SC_CHAR_MAX
	_SC_CHAR_MIN
	_SC_INT_MAX
	_SC_INT_MIN
	_SC_LONG_BIT
	_SC_WORD_BIT
	_SC_MB_LEN_MAX
	_SC_NZERO
	_SC_SSIZE_MAX
	_SC_SCHAR_MAX
	_SC_SCHAR_MIN
	_SC_SHRT_MAX
	_SC_SHRT_MIN
	_SC_UCHAR_MAX
	_SC_UINT_MAX
	_SC_ULONG_MAX
	_SC_USHRT_MAX
	_SC_NL_ARGMAX
	_SC_NL_LANGMAX
	_SC_NL_MSGMAX
	_SC_NL_NMAX
	_SC_NL_SETMAX
	_SC_NL_TEXTMAX
	_SC_XBS5_ILP32_OFF32
	_SC_XBS5_ILP32_OFFBIG
	_SC_XBS5_LP64_OFF64
	_SC_XBS5_LPBIG_OFFBIG
	_SC_XOPEN_LEGACY
	_SC_XOPEN_REALTIME
	_SC_XOPEN_REALTIME_THREADS
	_SC_ADVISORY_INFO
	_SC_BARRIERS
	_SC_BASE
	_SC_C_LANG_SUPPORT
	_SC_C_LANG_SUPPORT_R
	_SC_CLOCK_SELECTION
	_SC_CPUTIME
	_SC_THREAD_CPUTIME
	_SC_DEVICE_IO
	_SC_DEVICE_SPECIFIC
	_SC_DEVICE_SPECIFIC_R
	_SC_FD_MGMT
	_SC_FIFO
	_SC_PIPE
	_SC_FILE_ATTRIBUTES
	_SC_FILE_LOCKING
	_SC_FILE_SYSTEM
	_SC_MONOTONIC_CLOCK
	_SC_MULTI_PROCESS
	_SC_SINGLE_PROCESS
	_SC_NETWORKING
	_SC_READER_WRITER_LOCKS
	_SC_SPIN_LOCKS
	_SC_REGEXP
	_SC_REGEX_VERSION
	_SC_SHELL
	_SC_SIGNALS
	_SC_SPAWN
	_SC_SPORADIC_SERVER
	_SC_THREAD_SPORADIC_SERVER
	_SC_SYSTEM_DATABASE
	_SC_SYSTEM_DATABASE_R
	_SC_TIMEOUTS
	_SC_TYPED_MEMORY_OBJECTS
	_SC_USER_GROUPS
	_SC_USER_GROUPS_R
	_SC_2_PBS
	_SC_2_PBS_ACCOUNTING
	_SC_2_PBS_LOCATE
	_SC_2_PBS_MESSAGE
	_SC_2_PBS_TRACK
	_SC_SYMLOOP_MAX
	_SC_STREAMS
	_SC_2_PBS_CHECKPOINT
	_SC_V6_ILP32_OFF32
	_SC_V6_ILP32_OFFBIG
	_SC_V6_LP64_OFF64
	_SC_V6_LPBIG_OFFBIG
	_SC_HOST_NAME_MAX
	_SC_TRACE
	_SC_TRACE_EVENT_FILTER
	_SC_TRACE_INHERIT
	_SC_TRACE_LOG
	_SC_LEVEL1_ICACHE_SIZE
	_SC_LEVEL1_ICACHE_ASSOC
	_SC_LEVEL1_ICACHE_LINESIZE
	_SC_LEVEL1_DCACHE_SIZE
	_SC_LEVEL1_DCACHE_ASSOC
	_SC_LEVEL1_DCACHE_LINESIZE
	_SC_LEVEL2_CACHE_SIZE
	_SC_LEVEL2_CACHE_ASSOC
	_SC_LEVEL2_CACHE_LINESIZE
	_SC_LEVEL3_CACHE_SIZE
	_SC_LEVEL3_CACHE_ASSOC
	_SC_LEVEL3_CACHE_LINESIZE
	_SC_LEVEL4_CACHE_SIZE
	_SC_LEVEL4_CACHE_ASSOC
	_SC_LEVEL4_CACHE_LINESIZE
	(_SC_IPV6 #.(cl:+ _SC_LEVEL1_ICACHE_SIZE 50))
	_SC_RAW_SOCKETS
	_SC_V7_ILP32_OFF32
	_SC_V7_ILP32_OFFBIG
	_SC_V7_LP64_OFF64
	_SC_V7_LPBIG_OFFBIG
	_SC_SS_REPL_MAX
	_SC_TRACE_EVENT_NAME_MAX
	_SC_TRACE_NAME_MAX
	_SC_TRACE_SYS_MAX
	_SC_TRACE_USER_EVENT_MAX
	_SC_XOPEN_STREAMS
	_SC_THREAD_ROBUST_PRIO_INHERIT
	_SC_THREAD_ROBUST_PRIO_PROTECT)

(defanonenum 
	_CS_PATH
	_CS_V6_WIDTH_RESTRICTED_ENVS
	_CS_GNU_LIBC_VERSION
	_CS_GNU_LIBPTHREAD_VERSION
	_CS_V5_WIDTH_RESTRICTED_ENVS
	_CS_V7_WIDTH_RESTRICTED_ENVS
	(_CS_LFS_CFLAGS #.1000)
	_CS_LFS_LDFLAGS
	_CS_LFS_LIBS
	_CS_LFS_LINTFLAGS
	_CS_LFS64_CFLAGS
	_CS_LFS64_LDFLAGS
	_CS_LFS64_LIBS
	_CS_LFS64_LINTFLAGS
	(_CS_XBS5_ILP32_OFF32_CFLAGS #.1100)
	_CS_XBS5_ILP32_OFF32_LDFLAGS
	_CS_XBS5_ILP32_OFF32_LIBS
	_CS_XBS5_ILP32_OFF32_LINTFLAGS
	_CS_XBS5_ILP32_OFFBIG_CFLAGS
	_CS_XBS5_ILP32_OFFBIG_LDFLAGS
	_CS_XBS5_ILP32_OFFBIG_LIBS
	_CS_XBS5_ILP32_OFFBIG_LINTFLAGS
	_CS_XBS5_LP64_OFF64_CFLAGS
	_CS_XBS5_LP64_OFF64_LDFLAGS
	_CS_XBS5_LP64_OFF64_LIBS
	_CS_XBS5_LP64_OFF64_LINTFLAGS
	_CS_XBS5_LPBIG_OFFBIG_CFLAGS
	_CS_XBS5_LPBIG_OFFBIG_LDFLAGS
	_CS_XBS5_LPBIG_OFFBIG_LIBS
	_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS
	_CS_POSIX_V6_ILP32_OFF32_CFLAGS
	_CS_POSIX_V6_ILP32_OFF32_LDFLAGS
	_CS_POSIX_V6_ILP32_OFF32_LIBS
	_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_LIBS
	_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
	_CS_POSIX_V6_LP64_OFF64_CFLAGS
	_CS_POSIX_V6_LP64_OFF64_LDFLAGS
	_CS_POSIX_V6_LP64_OFF64_LIBS
	_CS_POSIX_V6_LP64_OFF64_LINTFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_LIBS
	_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
	_CS_POSIX_V7_ILP32_OFF32_CFLAGS
	_CS_POSIX_V7_ILP32_OFF32_LDFLAGS
	_CS_POSIX_V7_ILP32_OFF32_LIBS
	_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS
	_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
	_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
	_CS_POSIX_V7_ILP32_OFFBIG_LIBS
	_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS
	_CS_POSIX_V7_LP64_OFF64_CFLAGS
	_CS_POSIX_V7_LP64_OFF64_LDFLAGS
	_CS_POSIX_V7_LP64_OFF64_LIBS
	_CS_POSIX_V7_LP64_OFF64_LINTFLAGS
	_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
	_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
	_CS_POSIX_V7_LPBIG_OFFBIG_LIBS
	_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS
	_CS_V6_ENV
	_CS_V7_ENV)

(cffi:defcfun ("pathconf" pathconf) :long
  (__path :string)
  (__name :int))

(cffi:defcfun ("fpathconf" fpathconf) :long
  (__fd :int)
  (__name :int))

(cffi:defcfun ("sysconf" sysconf) :long
  (__name :int))

(cffi:defcfun ("confstr" confstr) :unsigned-long
  (__name :int)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("getpid" getpid) :int)

(cffi:defcfun ("getppid" getppid) :int)

(cffi:defcfun ("getpgrp" getpgrp) :int)

(cffi:defcfun ("__getpgid" __getpgid) :int
  (__pid :int))

(cffi:defcfun ("getpgid" getpgid) :int
  (__pid :int))

(cffi:defcfun ("setpgid" setpgid) :int
  (__pid :int)
  (__pgid :int))

(cffi:defcfun ("setpgrp" setpgrp) :int)

(cffi:defcfun ("setsid" setsid) :int)

(cffi:defcfun ("getsid" getsid) :int
  (__pid :int))

(cffi:defcfun ("getuid" getuid) :unsigned-int)

(cffi:defcfun ("geteuid" geteuid) :unsigned-int)

(cffi:defcfun ("getgid" getgid) :unsigned-int)

(cffi:defcfun ("getegid" getegid) :unsigned-int)

(cffi:defcfun ("getgroups" getgroups) :int
  (__size :int)
  (__list :pointer))

(cffi:defcfun ("setuid" setuid) :int
  (__uid :unsigned-int))

(cffi:defcfun ("setreuid" setreuid) :int
  (__ruid :unsigned-int)
  (__euid :unsigned-int))

(cffi:defcfun ("seteuid" seteuid) :int
  (__uid :unsigned-int))

(cffi:defcfun ("setgid" setgid) :int
  (__gid :unsigned-int))

(cffi:defcfun ("setregid" setregid) :int
  (__rgid :unsigned-int)
  (__egid :unsigned-int))

(cffi:defcfun ("setegid" setegid) :int
  (__gid :unsigned-int))

(cffi:defcfun ("fork" fork) :int)

(cffi:defcfun ("vfork" vfork) :int)

(cffi:defcfun ("ttyname" ttyname) :string
  (__fd :int))

(cffi:defcfun ("ttyname_r" ttyname_r) :int
  (__fd :int)
  (__buf :string)
  (__buflen :unsigned-long))

(cffi:defcfun ("isatty" isatty) :int
  (__fd :int))

(cffi:defcfun ("ttyslot" ttyslot) :int)

(cffi:defcfun ("link" link) :int
  (__from :string)
  (__to :string))

(cffi:defcfun ("linkat" linkat) :int
  (__fromfd :int)
  (__from :string)
  (__tofd :int)
  (__to :string)
  (__flags :int))

(cffi:defcfun ("symlink" symlink) :int
  (__from :string)
  (__to :string))

(cffi:defcfun ("readlink" readlink) :int
  (__path :string)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("symlinkat" symlinkat) :int
  (__from :string)
  (__tofd :int)
  (__to :string))

(cffi:defcfun ("readlinkat" readlinkat) :int
  (__fd :int)
  (__path :string)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("unlink" unlink) :int
  (__name :string))

(cffi:defcfun ("unlinkat" unlinkat) :int
  (__fd :int)
  (__name :string)
  (__flag :int))

(cffi:defcfun ("rmdir" rmdir) :int
  (__path :string))

(cffi:defcfun ("tcgetpgrp" tcgetpgrp) :int
  (__fd :int))

(cffi:defcfun ("tcsetpgrp" tcsetpgrp) :int
  (__fd :int)
  (__pgrp_id :int))

(cffi:defcfun ("getlogin" getlogin) :string)

(cffi:defcfun ("getlogin_r" getlogin_r) :int
  (__name :string)
  (__name_len :unsigned-long))

(cffi:defcfun ("setlogin" setlogin) :int
  (__name :string))

(cffi:defcvar ("optarg" optarg)
 :string)

(cffi:defcvar ("optind" optind)
 :int)

(cffi:defcvar ("opterr" opterr)
 :int)

(cffi:defcvar ("optopt" optopt)
 :int)

(cffi:defcfun ("getopt" getopt) :int
  (___argc :int)
  (___argv :pointer)
  (__shortopts :string))

(cffi:defcfun ("gethostname" gethostname) :int
  (__name :string)
  (__len :unsigned-long))

(cffi:defcfun ("sethostname" sethostname) :int
  (__name :string)
  (__len :unsigned-long))

(cffi:defcfun ("sethostid" sethostid) :int
  (__id :long))

(cffi:defcfun ("getdomainname" getdomainname) :int
  (__name :string)
  (__len :unsigned-long))

(cffi:defcfun ("setdomainname" setdomainname) :int
  (__name :string)
  (__len :unsigned-long))

(cffi:defcfun ("vhangup" vhangup) :int)

(cffi:defcfun ("revoke" revoke) :int
  (__file :string))

(cffi:defcfun ("profil" profil) :int
  (__sample_buffer :pointer)
  (__size :unsigned-long)
  (__offset :unsigned-long)
  (__scale :unsigned-int))

(cffi:defcfun ("acct" acct) :int
  (__name :string))

(cffi:defcfun ("getusershell" getusershell) :string)

(cffi:defcfun ("endusershell" endusershell) :void)

(cffi:defcfun ("setusershell" setusershell) :void)

(cffi:defcfun ("daemon" daemon) :int
  (__nochdir :int)
  (__noclose :int))

(cffi:defcfun ("chroot" chroot) :int
  (__path :string))

(cffi:defcfun ("getpass" getpass) :string
  (__prompt :string))

(cffi:defcfun ("fsync" fsync) :int
  (__fd :int))

(cffi:defcfun ("gethostid" gethostid) :long)

(cffi:defcfun ("sync" sync) :void)

(cffi:defcfun ("getpagesize" getpagesize) :int)

(cffi:defcfun ("getdtablesize" getdtablesize) :int)

(cffi:defcfun ("truncate" truncate) :int
  (__file :string)
  (__length :long))

(cffi:defcfun ("ftruncate" ftruncate) :int
  (__fd :int)
  (__length :long))

(cffi:defcfun ("brk" brk) :int
  (__addr :pointer))

(cffi:defcfun ("sbrk" sbrk) :pointer
  (__delta :int))

(cffi:defcfun ("syscall" syscall) :long
  (__sysno :long)
  &rest)

(cl:defconstant F_ULOCK 0)

(cl:defconstant F_LOCK 1)

(cl:defconstant F_TLOCK 2)

(cl:defconstant F_TEST 3)

(cffi:defcfun ("lockf" lockf) :int
  (__fd :int)
  (__cmd :int)
  (__len :long))

(cffi:defcfun ("fdatasync" fdatasync) :int
  (__fildes :int))

(cl:defconstant _STDLIB_H 1)

(cl:defconstant WNOHANG 1)

(cl:defconstant WUNTRACED 2)

(cl:defconstant WSTOPPED 2)

(cl:defconstant WEXITED 4)

(cl:defconstant WCONTINUED 8)

(cl:defconstant WNOWAIT #x01000000)

(cl:defconstant __WNOTHREAD #x20000000)

(cl:defconstant __WALL #x40000000)

(cl:defconstant __WCLONE #x80000000)

(cl:defconstant __W_CONTINUED #xffff)

(cl:defconstant __WCOREFLAG #x80)

(cl:defconstant _ENDIAN_H 1)

(cl:defconstant __LITTLE_ENDIAN 1234)

(cl:defconstant __BIG_ENDIAN 4321)

(cl:defconstant __PDP_ENDIAN 3412)

(cl:defconstant __BYTE_ORDER 1234)

(cl:defconstant __FLOAT_WORD_ORDER 1234)

(cl:defconstant LITTLE_ENDIAN 1234)

(cl:defconstant BIG_ENDIAN 4321)

(cl:defconstant PDP_ENDIAN 3412)

(cl:defconstant BYTE_ORDER 1234)

(cl:defconstant _BITS_BYTESWAP_H 1)

(cffi:defcfun ("__bswap_16" __bswap_16) :unsigned-short
  (__bsx :unsigned-short))

(cffi:defcfun ("__bswap_32" __bswap_32) :unsigned-int
  (__bsx :unsigned-int))

(cffi:defcfun ("__bswap_64" __bswap_64) :unsigned-long-long
  (__bsx :unsigned-long-long))

(cffi:defcunion wait
	(w_status :int)
	(__wait_terminated :pointer)
	(__wait_stopped :pointer))

(cffi:defcstruct wait___wait_stopped
	(__w_stopval :unsigned-int)
	(__w_stopsig :unsigned-int))

(cffi:defcstruct wait___wait_terminated
	(__w_termsig :unsigned-int)
	(__w_coredump :unsigned-int)
	(__w_retcode :unsigned-int))

(cffi:defcstruct div_t
	(quot :int)
	(rem :int))

(cffi:defcstruct ldiv_t
	(quot :long)
	(rem :long))

(cl:defconstant __ldiv_t_defined 1)

(cffi:defcstruct lldiv_t
	(quot :long-long)
	(rem :long-long))

(cl:defconstant __lldiv_t_defined 1)

(cl:defconstant RAND_MAX 2147483647)

(cl:defconstant EXIT_FAILURE 1)

(cl:defconstant EXIT_SUCCESS 0)

(cffi:defcfun ("__ctype_get_mb_cur_max" __ctype_get_mb_cur_max) :unsigned-long)

(cffi:defcfun ("atof" atof) :double
  (__nptr :string))

(cffi:defcfun ("atoi" atoi) :int
  (__nptr :string))

(cffi:defcfun ("atol" atol) :long
  (__nptr :string))

(cffi:defcfun ("atoll" atoll) :long-long
  (__nptr :string))

(cffi:defcfun ("strtod" strtod) :double
  (__nptr :string)
  (__endptr :pointer))

(cffi:defcfun ("strtof" strtof) :float
  (__nptr :string)
  (__endptr :pointer))

(cffi:defcfun ("strtold" strtold) :pointer
  (__nptr :string)
  (__endptr :pointer))

(cffi:defcfun ("strtol" strtol) :long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("strtoul" strtoul) :unsigned-long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("strtoq" strtoq) :long-long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("strtouq" strtouq) :unsigned-long-long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("strtoll" strtoll) :long-long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("strtoull" strtoull) :unsigned-long-long
  (__nptr :string)
  (__endptr :pointer)
  (__base :int))

(cffi:defcfun ("l64a" l64a) :string
  (__n :long))

(cffi:defcfun ("a64l" a64l) :long
  (__s :string))

(cl:defconstant _SYS_TYPES_H 1)

(cl:defconstant __clock_t_defined 1)

(cl:defconstant __time_t_defined 1)

(cl:defconstant __clockid_t_defined 1)

(cl:defconstant __timer_t_defined 1)

(cl:defconstant __BIT_TYPES_DEFINED__ 1)

(cl:defconstant _SYS_SELECT_H 1)

(cl:defconstant _SIGSET_H_types 1)

(cffi:defcstruct __sigset_t
	(__val :pointer))

(cl:defconstant _STRUCT_TIMEVAL 1)

(cffi:defcstruct timeval
	(tv_sec :long)
	(tv_usec :long))

(cffi:defcstruct fd_set
	(__fds_bits :pointer))

(cl:defconstant FD_SETSIZE 1024)

(cffi:defcfun ("select" select) :int
  (__nfds :int)
  (__readfds :pointer)
  (__writefds :pointer)
  (__exceptfds :pointer)
  (__timeout :pointer))

(cffi:defcfun ("pselect" pselect) :int
  (__nfds :int)
  (__readfds :pointer)
  (__writefds :pointer)
  (__exceptfds :pointer)
  (__timeout :pointer)
  (__sigmask :pointer))

(cl:defconstant _SYS_SYSMACROS_H 1)

(cffi:defcfun ("gnu_dev_major" gnu_dev_major) :unsigned-int
  (__dev :unsigned-long-long))

(cffi:defcfun ("gnu_dev_minor" gnu_dev_minor) :unsigned-int
  (__dev :unsigned-long-long))

(cffi:defcfun ("gnu_dev_makedev" gnu_dev_makedev) :unsigned-long-long
  (__major :unsigned-int)
  (__minor :unsigned-int))

(cl:defconstant _BITS_PTHREADTYPES_H 1)

(cl:defconstant __SIZEOF_PTHREAD_ATTR_T 36)

(cl:defconstant __SIZEOF_PTHREAD_MUTEX_T 24)

(cl:defconstant __SIZEOF_PTHREAD_MUTEXATTR_T 4)

(cl:defconstant __SIZEOF_PTHREAD_COND_T 48)

(cl:defconstant __SIZEOF_PTHREAD_CONDATTR_T 4)

(cl:defconstant __SIZEOF_PTHREAD_RWLOCK_T 32)

(cl:defconstant __SIZEOF_PTHREAD_RWLOCKATTR_T 8)

(cl:defconstant __SIZEOF_PTHREAD_BARRIER_T 20)

(cl:defconstant __SIZEOF_PTHREAD_BARRIERATTR_T 4)

(cffi:defcunion pthread_attr_t
	(__size :pointer)
	(__align :long))

(cl:defconstant __have_pthread_attr_t 1)

(cffi:defcstruct __pthread_slist_t
	(__next :pointer))

(cffi:defcunion pthread_mutex_t
	(__data :pointer)
	(__size :pointer)
	(__align :long))

(cffi:defcstruct __pthread_mutex_s
	(__lock :int)
	(__count :unsigned-int)
	(__owner :int)
	(__kind :int)
	(__nusers :unsigned-int)
	(d :pointer)
	(__list __pthread_slist_t))

(cffi:defcunion pthread_mutexattr_t
	(__size :pointer)
	(__align :int))

(cffi:defcunion pthread_cond_t
	(__data :pointer)
	(__size :pointer)
	(__align :long-long))

(cffi:defcstruct pthread_cond_t___data
	(__lock :int)
	(__futex :unsigned-int)
	(__total_seq :unsigned-long-long)
	(__wakeup_seq :unsigned-long-long)
	(__woken_seq :unsigned-long-long)
	(__mutex :pointer)
	(__nwaiters :unsigned-int)
	(__broadcast_seq :unsigned-int))

(cffi:defcunion pthread_condattr_t
	(__size :pointer)
	(__align :int))

(cffi:defcunion pthread_rwlock_t
	(__data :pointer)
	(__size :pointer)
	(__align :long))

(cffi:defcstruct pthread_rwlock_t___data
	(__lock :int)
	(__nr_readers :unsigned-int)
	(__readers_wakeup :unsigned-int)
	(__writer_wakeup :unsigned-int)
	(__nr_readers_queued :unsigned-int)
	(__nr_writers_queued :unsigned-int)
	(__flags :unsigned-char)
	(__shared :unsigned-char)
	(__pad1 :unsigned-char)
	(__pad2 :unsigned-char)
	(__writer :int))

(cffi:defcunion pthread_rwlockattr_t
	(__size :pointer)
	(__align :long))

(cffi:defcunion pthread_barrier_t
	(__size :pointer)
	(__align :long))

(cffi:defcunion pthread_barrierattr_t
	(__size :pointer)
	(__align :int))

(cffi:defcfun ("random" random) :long)

(cffi:defcfun ("srandom" srandom) :void
  (__seed :unsigned-int))

(cffi:defcfun ("initstate" initstate) :string
  (__seed :unsigned-int)
  (__statebuf :string)
  (__statelen :unsigned-long))

(cffi:defcfun ("setstate" setstate) :string
  (__statebuf :string))

(cffi:defcstruct random_data
	(fptr :pointer)
	(rptr :pointer)
	(state :pointer)
	(rand_type :int)
	(rand_deg :int)
	(rand_sep :int)
	(end_ptr :pointer))

(cffi:defcfun ("random_r" random_r) :int
  (__buf :pointer)
  (__result :pointer))

(cffi:defcfun ("srandom_r" srandom_r) :int
  (__seed :unsigned-int)
  (__buf :pointer))

(cffi:defcfun ("initstate_r" initstate_r) :int
  (__seed :unsigned-int)
  (__statebuf :string)
  (__statelen :unsigned-long)
  (__buf :pointer))

(cffi:defcfun ("setstate_r" setstate_r) :int
  (__statebuf :string)
  (__buf :pointer))

(cffi:defcfun ("rand" rand) :int)

(cffi:defcfun ("srand" srand) :void
  (__seed :unsigned-int))

(cffi:defcfun ("rand_r" rand_r) :int
  (__seed :pointer))

(cffi:defcfun ("drand48" drand48) :double)

(cffi:defcfun ("erand48" erand48) :double
  (__xsubi :pointer))

(cffi:defcfun ("lrand48" lrand48) :long)

(cffi:defcfun ("nrand48" nrand48) :long
  (__xsubi :pointer))

(cffi:defcfun ("mrand48" mrand48) :long)

(cffi:defcfun ("jrand48" jrand48) :long
  (__xsubi :pointer))

(cffi:defcfun ("srand48" srand48) :void
  (__seedval :long))

(cffi:defcfun ("seed48" seed48) :pointer
  (__seed16v :pointer))

(cffi:defcfun ("lcong48" lcong48) :void
  (__param :pointer))

(cffi:defcstruct drand48_data
	(__x :pointer)
	(__old_x :pointer)
	(__c :unsigned-short)
	(__init :unsigned-short)
	(__a :unsigned-long-long))

(cffi:defcfun ("drand48_r" drand48_r) :int
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("erand48_r" erand48_r) :int
  (__xsubi :pointer)
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("lrand48_r" lrand48_r) :int
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("nrand48_r" nrand48_r) :int
  (__xsubi :pointer)
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("mrand48_r" mrand48_r) :int
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("jrand48_r" jrand48_r) :int
  (__xsubi :pointer)
  (__buffer :pointer)
  (__result :pointer))

(cffi:defcfun ("srand48_r" srand48_r) :int
  (__seedval :long)
  (__buffer :pointer))

(cffi:defcfun ("seed48_r" seed48_r) :int
  (__seed16v :pointer)
  (__buffer :pointer))

(cffi:defcfun ("lcong48_r" lcong48_r) :int
  (__param :pointer)
  (__buffer :pointer))

(cffi:defcfun ("malloc" malloc) :pointer
  (__size :unsigned-long))

(cffi:defcfun ("calloc" calloc) :pointer
  (__nmemb :unsigned-long)
  (__size :unsigned-long))

(cffi:defcfun ("realloc" realloc) :pointer
  (__ptr :pointer)
  (__size :unsigned-long))

(cffi:defcfun ("free" free) :void
  (__ptr :pointer))

(cffi:defcfun ("cfree" cfree) :void
  (__ptr :pointer))

(cl:defconstant _ALLOCA_H 1)

(cffi:defcfun ("alloca" alloca) :pointer
  (__size :unsigned-long))

(cffi:defcfun ("valloc" valloc) :pointer
  (__size :unsigned-long))

(cffi:defcfun ("posix_memalign" posix_memalign) :int
  (__memptr :pointer)
  (__alignment :unsigned-long)
  (__size :unsigned-long))

(cffi:defcfun ("abort" abort) :void)

(cffi:defcfun ("atexit" atexit) :int
  (__func :pointer))

(cffi:defcfun ("on_exit" on_exit) :int
  (__func :pointer)
  (__arg :pointer))

(cffi:defcfun ("exit" exit) :void
  (__status :int))

(cffi:defcfun ("_Exit" _Exit) :void
  (__status :int))

(cffi:defcfun ("getenv" getenv) :string
  (__name :string))

(cffi:defcfun ("putenv" putenv) :int
  (__string :string))

(cffi:defcfun ("setenv" setenv) :int
  (__name :string)
  (__value :string)
  (__replace :int))

(cffi:defcfun ("unsetenv" unsetenv) :int
  (__name :string))

(cffi:defcfun ("clearenv" clearenv) :int)

(cffi:defcfun ("mktemp" mktemp) :string
  (__template :string))

(cffi:defcfun ("mkstemp" mkstemp) :int
  (__template :string))

(cffi:defcfun ("mkstemps" mkstemps) :int
  (__template :string)
  (__suffixlen :int))

(cffi:defcfun ("mkdtemp" mkdtemp) :string
  (__template :string))

(cffi:defcfun ("system" system) :int
  (__command :string))

(cffi:defcfun ("realpath" realpath) :string
  (__name :string)
  (__resolved :string))

(cffi:defcfun ("bsearch" bsearch) :pointer
  (__key :pointer)
  (__base :pointer)
  (__nmemb :unsigned-long)
  (__size :unsigned-long)
  (__compar :pointer))

(cffi:defcfun ("qsort" qsort) :void
  (__base :pointer)
  (__nmemb :unsigned-long)
  (__size :unsigned-long)
  (__compar :pointer))

(cffi:defcfun ("abs" abs) :int
  (__x :int))

(cffi:defcfun ("labs" labs) :long
  (__x :long))

(cffi:defcfun ("llabs" llabs) :long-long
  (__x :long-long))

(cffi:defcfun ("div" div) div_t
  (__numer :int)
  (__denom :int))

(cffi:defcfun ("ldiv" ldiv) ldiv_t
  (__numer :long)
  (__denom :long))

(cffi:defcfun ("lldiv" lldiv) lldiv_t
  (__numer :long-long)
  (__denom :long-long))

(cffi:defcfun ("ecvt" ecvt) :string
  (__value :double)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer))

(cffi:defcfun ("fcvt" fcvt) :string
  (__value :double)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer))

(cffi:defcfun ("gcvt" gcvt) :string
  (__value :double)
  (__ndigit :int)
  (__buf :string))

(cffi:defcfun ("qecvt" qecvt) :string
  (__value :pointer)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer))

(cffi:defcfun ("qfcvt" qfcvt) :string
  (__value :pointer)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer))

(cffi:defcfun ("qgcvt" qgcvt) :string
  (__value :pointer)
  (__ndigit :int)
  (__buf :string))

(cffi:defcfun ("ecvt_r" ecvt_r) :int
  (__value :double)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("fcvt_r" fcvt_r) :int
  (__value :double)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("qecvt_r" qecvt_r) :int
  (__value :pointer)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("qfcvt_r" qfcvt_r) :int
  (__value :pointer)
  (__ndigit :int)
  (__decpt :pointer)
  (__sign :pointer)
  (__buf :string)
  (__len :unsigned-long))

(cffi:defcfun ("mblen" mblen) :int
  (__s :string)
  (__n :unsigned-long))

(cffi:defcfun ("mbtowc" mbtowc) :int
  (__pwc :pointer)
  (__s :string)
  (__n :unsigned-long))

(cffi:defcfun ("wctomb" wctomb) :int
  (__s :string)
  (__wchar :pointer))

(cffi:defcfun ("mbstowcs" mbstowcs) :unsigned-long
  (__pwcs :pointer)
  (__s :string)
  (__n :unsigned-long))

(cffi:defcfun ("wcstombs" wcstombs) :unsigned-long
  (__s :string)
  (__pwcs :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("rpmatch" rpmatch) :int
  (__response :string))

(cffi:defcfun ("getsubopt" getsubopt) :int
  (__optionp :pointer)
  (__tokens :pointer)
  (__valuep :pointer))

(cffi:defcfun ("getloadavg" getloadavg) :int
  (__loadavg :pointer)
  (__nelem :int))

(cl:defconstant _STDINT_H 1)

(cl:defconstant _BITS_WCHAR_H 1)

(cl:defconstant __WCHAR_MAX (cl:+ #x7fffffff \\0))

(cl:defconstant __WCHAR_MIN (cl:+ -(0x7fffffff (cl:- \\0) 1)))

(cl:defconstant INT8_MIN -128)

(cl:defconstant INT16_MIN (cl:- 32767 1))

(cl:defconstant INT32_MIN (cl:- 2147483647 1))

(cl:defconstant INT64_MIN (cl:- 9223372036854775807LL 1))

(cl:defconstant INT8_MAX 127)

(cl:defconstant INT16_MAX 32767)

(cl:defconstant INT32_MAX 2147483647)

(cl:defconstant INT64_MAX 9223372036854775807LL)

(cl:defconstant UINT8_MAX 255)

(cl:defconstant UINT16_MAX 65535)

(cl:defconstant UINT32_MAX 4294967295)

(cl:defconstant UINT64_MAX 18446744073709551615ULL)

(cl:defconstant INT_LEAST8_MIN -128)

(cl:defconstant INT_LEAST16_MIN (cl:- 32767 1))

(cl:defconstant INT_LEAST32_MIN (cl:- 2147483647 1))

(cl:defconstant INT_LEAST64_MIN (cl:- 9223372036854775807LL 1))

(cl:defconstant INT_LEAST8_MAX 127)

(cl:defconstant INT_LEAST16_MAX 32767)

(cl:defconstant INT_LEAST32_MAX 2147483647)

(cl:defconstant INT_LEAST64_MAX 9223372036854775807LL)

(cl:defconstant UINT_LEAST8_MAX 255)

(cl:defconstant UINT_LEAST16_MAX 65535)

(cl:defconstant UINT_LEAST32_MAX 4294967295)

(cl:defconstant UINT_LEAST64_MAX 18446744073709551615ULL)

(cl:defconstant INT_FAST8_MIN -128)

(cl:defconstant INT_FAST16_MIN (cl:- 2147483647 1))

(cl:defconstant INT_FAST32_MIN (cl:- 2147483647 1))

(cl:defconstant INT_FAST64_MIN (cl:- 9223372036854775807LL 1))

(cl:defconstant INT_FAST8_MAX 127)

(cl:defconstant INT_FAST16_MAX 2147483647)

(cl:defconstant INT_FAST32_MAX 2147483647)

(cl:defconstant INT_FAST64_MAX 9223372036854775807LL)

(cl:defconstant UINT_FAST8_MAX 255)

(cl:defconstant UINT_FAST16_MAX 4294967295)

(cl:defconstant UINT_FAST32_MAX 4294967295)

(cl:defconstant UINT_FAST64_MAX 18446744073709551615ULL)

(cl:defconstant INTPTR_MIN (cl:- 2147483647 1))

(cl:defconstant INTPTR_MAX 2147483647)

(cl:defconstant UINTPTR_MAX 4294967295)

(cl:defconstant INTMAX_MIN (cl:- 9223372036854775807LL 1))

(cl:defconstant INTMAX_MAX 9223372036854775807LL)

(cl:defconstant UINTMAX_MAX 18446744073709551615ULL)

(cl:defconstant PTRDIFF_MIN (cl:- 2147483647 1))

(cl:defconstant PTRDIFF_MAX 2147483647)

(cl:defconstant SIG_ATOMIC_MIN (cl:- 2147483647 1))

(cl:defconstant SIG_ATOMIC_MAX 2147483647)

(cl:defconstant SIZE_MAX 4294967295)

(cl:defconstant WCHAR_MIN (cl:+ -(0x7fffffff (cl:- \\0) 1)))

(cl:defconstant WCHAR_MAX (cl:+ #x7fffffff \\0))

(cl:defconstant WINT_MIN 0)

(cl:defconstant WINT_MAX 4294967295)

(cl:defconstant _STRING_H 1)

(cffi:defcfun ("memcpy" memcpy) :pointer
  (__dest :pointer)
  (__src :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("memmove" memmove) :pointer
  (__dest :pointer)
  (__src :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("memccpy" memccpy) :pointer
  (__dest :pointer)
  (__src :pointer)
  (__c :int)
  (__n :unsigned-long))

(cffi:defcfun ("memset" memset) :pointer
  (__s :pointer)
  (__c :int)
  (__n :unsigned-long))

(cffi:defcfun ("memcmp" memcmp) :int
  (__s1 :pointer)
  (__s2 :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("memchr" memchr) :pointer
  (__s :pointer)
  (__c :int)
  (__n :unsigned-long))

(cffi:defcfun ("strcpy" strcpy) :string
  (__dest :string)
  (__src :string))

(cffi:defcfun ("strncpy" strncpy) :string
  (__dest :string)
  (__src :string)
  (__n :unsigned-long))

(cffi:defcfun ("strcat" strcat) :string
  (__dest :string)
  (__src :string))

(cffi:defcfun ("strncat" strncat) :string
  (__dest :string)
  (__src :string)
  (__n :unsigned-long))

(cffi:defcfun ("strcmp" strcmp) :int
  (__s1 :string)
  (__s2 :string))

(cffi:defcfun ("strncmp" strncmp) :int
  (__s1 :string)
  (__s2 :string)
  (__n :unsigned-long))

(cffi:defcfun ("strcoll" strcoll) :int
  (__s1 :string)
  (__s2 :string))

(cffi:defcfun ("strxfrm" strxfrm) :unsigned-long
  (__dest :string)
  (__src :string)
  (__n :unsigned-long))

(cl:defconstant _XLOCALE_H 1)

(cffi:defcstruct __locale_struct
	(__locales :pointer)
	(__ctype_b :pointer)
	(__ctype_tolower :pointer)
	(__ctype_toupper :pointer)
	(__names :pointer))

(cffi:defcfun ("strcoll_l" strcoll_l) :int
  (__s1 :string)
  (__s2 :string)
  (__l :pointer))

(cffi:defcfun ("strxfrm_l" strxfrm_l) :unsigned-long
  (__dest :string)
  (__src :string)
  (__n :unsigned-long)
  (__l :pointer))

(cffi:defcfun ("strdup" strdup) :string
  (__s :string))

(cffi:defcfun ("strndup" strndup) :string
  (__string :string)
  (__n :unsigned-long))

(cffi:defcfun ("strchr" strchr) :string
  (__s :string)
  (__c :int))

(cffi:defcfun ("strrchr" strrchr) :string
  (__s :string)
  (__c :int))

(cffi:defcfun ("strcspn" strcspn) :unsigned-long
  (__s :string)
  (__reject :string))

(cffi:defcfun ("strspn" strspn) :unsigned-long
  (__s :string)
  (__accept :string))

(cffi:defcfun ("strpbrk" strpbrk) :string
  (__s :string)
  (__accept :string))

(cffi:defcfun ("strstr" strstr) :string
  (__haystack :string)
  (__needle :string))

(cffi:defcfun ("strtok" strtok) :string
  (__s :string)
  (__delim :string))

(cffi:defcfun ("__strtok_r" __strtok_r) :string
  (__s :string)
  (__delim :string)
  (__save_ptr :pointer))

(cffi:defcfun ("strtok_r" strtok_r) :string
  (__s :string)
  (__delim :string)
  (__save_ptr :pointer))

(cffi:defcfun ("strlen" strlen) :unsigned-long
  (__s :string))

(cffi:defcfun ("strnlen" strnlen) :unsigned-long
  (__string :string)
  (__maxlen :unsigned-long))

(cffi:defcfun ("strerror" strerror) :string
  (__errnum :int))

(cffi:defcfun ("__xpg_strerror_r" __xpg_strerror_r) :int
  (__errnum :int)
  (__buf :string)
  (__buflen :unsigned-long))

(cffi:defcfun ("strerror_l" strerror_l) :string
  (__errnum :int)
  (__l :pointer))

(cffi:defcfun ("__bzero" __bzero) :void
  (__s :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("bcopy" bcopy) :void
  (__src :pointer)
  (__dest :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("bzero" bzero) :void
  (__s :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("bcmp" bcmp) :int
  (__s1 :pointer)
  (__s2 :pointer)
  (__n :unsigned-long))

(cffi:defcfun ("index" index) :string
  (__s :string)
  (__c :int))

(cffi:defcfun ("rindex" rindex) :string
  (__s :string)
  (__c :int))

(cffi:defcfun ("ffs" ffs) :int
  (__i :int))

(cffi:defcfun ("strcasecmp" strcasecmp) :int
  (__s1 :string)
  (__s2 :string))

(cffi:defcfun ("strncasecmp" strncasecmp) :int
  (__s1 :string)
  (__s2 :string)
  (__n :unsigned-long))

(cffi:defcfun ("strsep" strsep) :string
  (__stringp :pointer)
  (__delim :string))

(cffi:defcfun ("strsignal" strsignal) :string
  (__sig :int))

(cffi:defcfun ("__stpcpy" __stpcpy) :string
  (__dest :string)
  (__src :string))

(cffi:defcfun ("stpcpy" stpcpy) :string
  (__dest :string)
  (__src :string))

(cffi:defcfun ("__stpncpy" __stpncpy) :string
  (__dest :string)
  (__src :string)
  (__n :unsigned-long))

(cffi:defcfun ("stpncpy" stpncpy) :string
  (__dest :string)
  (__src :string)
  (__n :unsigned-long))


