(ql:quickload :cl-ppcre)
(defpackage util
  (:export "system")
  (:use :COMMON-LISP :SB-EXT :CL-PPCRE))
(in-package :util)
(defun system (program &rest args)
  (let ((output-stream (make-string-output-stream)))
    (run-program program args :output output-stream
                        :search t :error :output :wait t)
    (get-output-stream-string output-stream)))
(defun run-shell-command (command)
  (system "/bin/bash" "-c" command))
(defun split-string (str)
  (split "\\s+" str))
(defun package-symbol-list (package &optional all)
  (let ((symbol-list nil))    
    (do-external-symbols (sym package)
      (push sym symbol-list))
    (sort symbol-list #'string<)))
