#define _GNU_SOURCE
#include <stdilib.h>
#define MZ_PRECISE_GC
#include <racket/escheme.h>

Scheme_Object* scheme_initialize(Scheme_Env *env);
Scheme_Object* scheme_reload(Scheme_Env *env);
Scheme_Object* scheme_module_name(void);
#if SIZEOF_VOID_P == 8
typedef int128 __int128;
typedef uint128 unsigned __int128;
typedef exfixnum uint128;
#else
typedef exfixnum uint64_t;
#endif

static Scheme_Type scheme_exfixnum
typedef struct Scheme_Exfixnum {
  Scheme_Object type;//16 or 32 bits depending on gc mode
  union {
    struct {uintptr_t fix1; uintptr_t fix2;};
    exfixnum ex;
  };  
};


#define add +
#define sub -
#define mul *
#define div /
#define lshift <<
#define rshift >>
#define xor ^
#define and &
#define or |
#define not ~

/*
  Hooray for non hygenic macros
*/
#define do_bytevector_primitive(type, op)                               \
  uint8_t *x_ptr = ((uint8_t*)SCHEME_BYTE_STR_VAL(x))+SCHEME_INT_VAL(x_idx); \
  uint8_t *y_ptr = ((uint8_t*)SCHEME_BYTE_STR_VAL(y))+SCHEME_INT_VAL(y_idx); \
  type x = *((type*)(x_ptr));                                           \
  type y = *((type*)(y_ptr));                                           \
  type z = x op y;

/*
  The functions generated by this don't do typechecking
*/
#define make_bytevector_primitive(type, op)                     \
  void scheme_bytevector_##op##_in_place(Scheme_Object *x_bv,   \
                                         Scheme_Object *x_idx,  \
                                         Scheme_Object *y_bv,   \
                                         Scheme_Object *y_idx){ \
    do_bytevector_primitive(type, op);                          \
    *((type*)(x_ptr)) = z;                                      \
    return;                                                     \
  }                                                             \
  type scheme_bytevector_##op(Scheme_Object *x_bv,              \
                              Scheme_Object *x_idx,             \
                              Scheme_Object *y_bv,              \
                              Scheme_Object *y_idx){            \
    do_bytevector_primitive(type, op);                          \
    return z;                                                   \
  }
