#lang racket
(define (serve port-no)
  (define listener (tcp-listen port-no 5 #t))
  (define (event-loop)
    (accept-and-handle listener)
    (event-loop))
  (event-loop))
(define (accept-and-handle listener)
  (define-values (in out) (tcp-accept listener))
  (handle in out)
  (close-input-port in)
  (close-output-port out))
(define (handle in out)
  (regexp-match #rx"(\n|^)\n" in)
  (display "HTTP/1.0 200 Okay\n" out)
  (display "Server: k\nContent-Type: text/html\n\n" out)
  (display "<html><body>Hello, World!</body></html>" out))
