# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package libmagic;
use base qw(Exporter);
use base qw(DynaLoader);
package libmagicc;
bootstrap libmagic;
package libmagic;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package libmagic;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package libmagic;

*magic_open = *libmagicc::magic_open;
*magic_close = *libmagicc::magic_close;
*magic_getpath = *libmagicc::magic_getpath;
*magic_file = *libmagicc::magic_file;
*magic_descriptor = *libmagicc::magic_descriptor;
*magic_buffer = *libmagicc::magic_buffer;
*magic_error = *libmagicc::magic_error;
*magic_setflags = *libmagicc::magic_setflags;
*magic_version = *libmagicc::magic_version;
*magic_load = *libmagicc::magic_load;
*magic_compile = *libmagicc::magic_compile;
*magic_check = *libmagicc::magic_check;
*magic_list = *libmagicc::magic_list;
*magic_errno = *libmagicc::magic_errno;

# ------- VARIABLE STUBS --------

package libmagic;

*MAGIC_NONE = *libmagicc::MAGIC_NONE;
*MAGIC_DEBUG = *libmagicc::MAGIC_DEBUG;
*MAGIC_SYMLINK = *libmagicc::MAGIC_SYMLINK;
*MAGIC_COMPRESS = *libmagicc::MAGIC_COMPRESS;
*MAGIC_DEVICES = *libmagicc::MAGIC_DEVICES;
*MAGIC_MIME_TYPE = *libmagicc::MAGIC_MIME_TYPE;
*MAGIC_CONTINUE = *libmagicc::MAGIC_CONTINUE;
*MAGIC_CHECK = *libmagicc::MAGIC_CHECK;
*MAGIC_PRESERVE_ATIME = *libmagicc::MAGIC_PRESERVE_ATIME;
*MAGIC_RAW = *libmagicc::MAGIC_RAW;
*MAGIC_ERROR = *libmagicc::MAGIC_ERROR;
*MAGIC_MIME_ENCODING = *libmagicc::MAGIC_MIME_ENCODING;
*MAGIC_MIME = *libmagicc::MAGIC_MIME;
*MAGIC_APPLE = *libmagicc::MAGIC_APPLE;
*MAGIC_NO_CHECK_COMPRESS = *libmagicc::MAGIC_NO_CHECK_COMPRESS;
*MAGIC_NO_CHECK_TAR = *libmagicc::MAGIC_NO_CHECK_TAR;
*MAGIC_NO_CHECK_SOFT = *libmagicc::MAGIC_NO_CHECK_SOFT;
*MAGIC_NO_CHECK_APPTYPE = *libmagicc::MAGIC_NO_CHECK_APPTYPE;
*MAGIC_NO_CHECK_ELF = *libmagicc::MAGIC_NO_CHECK_ELF;
*MAGIC_NO_CHECK_TEXT = *libmagicc::MAGIC_NO_CHECK_TEXT;
*MAGIC_NO_CHECK_CDF = *libmagicc::MAGIC_NO_CHECK_CDF;
*MAGIC_NO_CHECK_TOKENS = *libmagicc::MAGIC_NO_CHECK_TOKENS;
*MAGIC_NO_CHECK_ENCODING = *libmagicc::MAGIC_NO_CHECK_ENCODING;
*MAGIC_NO_CHECK_BUILTIN = *libmagicc::MAGIC_NO_CHECK_BUILTIN;
*MAGIC_NO_CHECK_ASCII = *libmagicc::MAGIC_NO_CHECK_ASCII;
*MAGIC_NO_CHECK_FORTRAN = *libmagicc::MAGIC_NO_CHECK_FORTRAN;
*MAGIC_NO_CHECK_TROFF = *libmagicc::MAGIC_NO_CHECK_TROFF;
*MAGIC_VERSION = *libmagicc::MAGIC_VERSION;
1;
