# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package magic;
use base qw(Exporter);
use base qw(DynaLoader);
package magicc;
bootstrap magic;
package magic;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package magic;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package magic;

*magic_open = *magicc::magic_open;
*magic_close = *magicc::magic_close;
*magic_getpath = *magicc::magic_getpath;
*magic_file = *magicc::magic_file;
*magic_descriptor = *magicc::magic_descriptor;
*magic_buffer = *magicc::magic_buffer;
*magic_error = *magicc::magic_error;
*magic_setflags = *magicc::magic_setflags;
*magic_version = *magicc::magic_version;
*magic_load = *magicc::magic_load;
*magic_compile = *magicc::magic_compile;
*magic_check = *magicc::magic_check;
*magic_list = *magicc::magic_list;
*magic_errno = *magicc::magic_errno;

# ------- VARIABLE STUBS --------

package magic;

*MAGIC_NONE = *magicc::MAGIC_NONE;
*MAGIC_DEBUG = *magicc::MAGIC_DEBUG;
*MAGIC_SYMLINK = *magicc::MAGIC_SYMLINK;
*MAGIC_COMPRESS = *magicc::MAGIC_COMPRESS;
*MAGIC_DEVICES = *magicc::MAGIC_DEVICES;
*MAGIC_MIME_TYPE = *magicc::MAGIC_MIME_TYPE;
*MAGIC_CONTINUE = *magicc::MAGIC_CONTINUE;
*MAGIC_CHECK = *magicc::MAGIC_CHECK;
*MAGIC_PRESERVE_ATIME = *magicc::MAGIC_PRESERVE_ATIME;
*MAGIC_RAW = *magicc::MAGIC_RAW;
*MAGIC_ERROR = *magicc::MAGIC_ERROR;
*MAGIC_MIME_ENCODING = *magicc::MAGIC_MIME_ENCODING;
*MAGIC_MIME = *magicc::MAGIC_MIME;
*MAGIC_APPLE = *magicc::MAGIC_APPLE;
*MAGIC_NO_CHECK_COMPRESS = *magicc::MAGIC_NO_CHECK_COMPRESS;
*MAGIC_NO_CHECK_TAR = *magicc::MAGIC_NO_CHECK_TAR;
*MAGIC_NO_CHECK_SOFT = *magicc::MAGIC_NO_CHECK_SOFT;
*MAGIC_NO_CHECK_APPTYPE = *magicc::MAGIC_NO_CHECK_APPTYPE;
*MAGIC_NO_CHECK_ELF = *magicc::MAGIC_NO_CHECK_ELF;
*MAGIC_NO_CHECK_TEXT = *magicc::MAGIC_NO_CHECK_TEXT;
*MAGIC_NO_CHECK_CDF = *magicc::MAGIC_NO_CHECK_CDF;
*MAGIC_NO_CHECK_TOKENS = *magicc::MAGIC_NO_CHECK_TOKENS;
*MAGIC_NO_CHECK_ENCODING = *magicc::MAGIC_NO_CHECK_ENCODING;
*MAGIC_NO_CHECK_BUILTIN = *magicc::MAGIC_NO_CHECK_BUILTIN;
*MAGIC_NO_CHECK_ASCII = *magicc::MAGIC_NO_CHECK_ASCII;
*MAGIC_NO_CHECK_FORTRAN = *magicc::MAGIC_NO_CHECK_FORTRAN;
*MAGIC_NO_CHECK_TROFF = *magicc::MAGIC_NO_CHECK_TROFF;
*MAGIC_VERSION = *magicc::MAGIC_VERSION;
1;
