#define _GNU_SOURCE
#include <stdilib.h>
#define MZ_PRECISE_GC
#include <racket/escheme.h>

Scheme_Object* scheme_initialize(Scheme_Env *env);
Scheme_Object* scheme_reload(Scheme_Env *env);
Scheme_Object* scheme_module_name(void);
#if SIZEOF_VOID_P == 8
typedef int128 __int128;
typedef uint128 unsigned __int128;
typedef exfixnum uint128;
#else
typedef exfixnum uint64_t;
#endif

static Scheme_Type scheme_exfixnum
typedef struct Scheme_Exfixnum {
  Scheme_Object type;//16 or 32 bits depending on gc mode
  union {
    struct {uintptr_t fix1; uintptr_t fix2;};
    exfixnum ex;
  };  
};


#define add +
#define sub -
#define mul *
#define div /
#define lshift <<
#define rshift >>
#define xor ^
#define and &
#define or |
#define not ~

/*
  x,y,x_ptr and y_ptr need to be defined when calling this.
  Hooray for non hygenic macros.
*/
#define do_bytevector_primitive(type, op)                               \
  uint8_t *x_ptr = ((uint8_t*)SCHEME_BYTE_STR_VAL(x))+SCHEME_INT_VAL(x_idx); \
  uint8_t *y_ptr = ((uint8_t*)SCHEME_BYTE_STR_VAL(y))+SCHEME_INT_VAL(y_idx); \
  type x = *((type*)(x_ptr));                                           \
  type y = *((type*)(y_ptr));                                           \
  type z = x op y;
#define do_bytevector_not(type)                                         \
  uint8_t *x_ptr = ((uint8_t*)SCHEME_BYTE_STR_VAL(x))+SCHEME_INT_VAL(x_idx); \
  type x = *((type*)(x_ptr));                                           \
  type z = ~(x);

/*
  The functions generated by this don't do typechecking
*/
#define make_bytevector_primitive(type, op)                             \
  void scheme_bytevector_##type##_##op##_in_place(Scheme_Object *x_bv,  \
                                                  Scheme_Object *x_idx, \
                                                  Scheme_Object *y_bv,  \
                                                  Scheme_Object *y_idx){ \
    do_bytevector_primitive(type, op);                                  \
    *((type*)(x_ptr)) = z;                                              \
    return;                                                             \
  }                                                                     \
  type scheme_bytevector_##type##_##op(Scheme_Object *x_bv,             \
                                       Scheme_Object *x_idx,            \
                                       Scheme_Object *y_bv,             \
                                       Scheme_Object *y_idx){           \
    do_bytevector_primitive(type, op);                                  \
    return z;                                                           \
  }
#define make_bytevector_not(type)                                       \
  void scheme_bytevector_##type##not_in_place(Scheme_Object *x_bv,      \
                                              Scheme_Object *x_idx){    \
    do_bytevector_not(type);                                            \
    *((type*)(x_ptr)) = z;                                              \
    return;                                                             \
  }                                                                     \
  type scheme_bytevector_##type##_not(Scheme_Object *x_bv,              \
                                      Scheme_Object *x_idx){            \
    do_bytevector_not(type);                                            \
    return z;                                                           \
  }
#define make_bytevector_primitives(type)        \
  make_bytevector_primitive(type, add);         \
  make_bytevector_primitive(type, sub);         \
  make_bytevector_primitive(type, mul);         \
  make_bytevector_primitive(type, div);         \
  make_bytevector_primitive(type, lshift);      \
  make_bytevector_primitive(type, rshift);      \
  make_bytevector_primitive(type, xor);         \
  make_bytevector_primitive(type, and);         \
  make_bytevector_primitive(type, or);          \
  make_bytevector_not(type);

typedef uint8 uint8_t;
typedef uint16 uint16_t;
typedef uint32 uint32_t;
typedef uint64 uint64_t;
make_bytevector_primitives(uint8);
make_bytevector_primitives(uint16);
make_bytevector_primitives(uint32);
make_bytevector_primitives(uint64);
